export { default as Login } from "./Login/Login"
export { default as Register } from "./Register/Register"
export { default as PasswordInputEmail } from "./ForgetPassword/InputEmail/InputEmail"
export { default as PasswordCheckEmail } from "./ForgetPassword/CheckEmail/CheckEmail"
export { default as ChangePassword } from "./ForgetPassword/ChangePassword/ChangePassword"
export { default as SuccessPasswordChange } from "./ForgetPassword/SuccessPasswordChange/SuccessPasswordChange"
export { default as FailedPasswordChange } from "./ForgetPassword/FailedChangePassword/FailedPasswordChange"