export { default as Logo } from "./Logo/logo.svg"
export { default as AmicoLogin } from "./Logo/amicoLogin.svg"
export { default as AmicoRegister } from "./Logo/amicoRegister.svg"
export { default as Google } from "./Logo/Google.svg"
export { default as Info } from "./icon/Info/Info.svg"