export { default as Logo } from "./Logo/logo.svg"
export { default as Google } from "./Logo/Google.svg"
export { default as IlustrationLogin } from "./Ilustration/IlustrationLogin.svg"
export { default as IlustrationRegister } from "./Ilustration/IlustrationRegister.svg"
export { default as IlustrationRegisterSuccess } from "./Ilustration/IlustrationRegisterSuccess.svg"
export { default as IlustrationForgetPasswordInputEmail } from "./Ilustration/IlustrationForgetPasswordInputEmail.svg"